[package]
name = "typed-hash-tree"
version = "0.0.0"
authors = ["David Holtz <david.richard.holtz@gmail.com>"]
edition = "2018"

[dependencies]
digest = "0.8.1"
sha2 = "0.8.1"
base64 = "0.12.0"
hex = "0.4.2"